apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: utilities
  source:
    repoURL: "https://github.com/jamie-oconnell/homelab.git"
    path: apps/utilities/crossplane
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-kustomize
  destination:
    namespace: crossplane
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    managedNamespaceMetadata:
      labels:
        prometheus: enabled
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=false
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
  info:
    - name: "Github Repository:"
      value: >-
        https://github.com/crossplane/crossplane
    - name: "Providers marketplace:"
      value: >-
        https://marketplace.upbound.io/
    - name: "Helm chart Github path:"
      value: >-
        https://github.com/crossplane/crossplane/tree/master/cluster/charts/crossplane
    - name: "Official docs:"
      value: >-
        https://docs.crossplane.io/latest/
