apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  project: utilities
  sources:
    - repoURL: https://github.com/hashicorp/vault-helm.git
      targetRevision: v0.28.1
      path: .
      helm:
        releaseName: vault
        valueFiles:
          - $values/apps/argocd/base/utilities/hashicorp-vault-values.yaml
    - repoURL: "https://github.com/jamie-oconnell/homelab.git"
      targetRevision: main
      ref: values
  destination:
    namespace: vault
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=false
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
