apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: kured
    releaseName: kured
    namespace: kube-system
    version: 5.5.0
    repo: https://kubereboot.github.io/charts
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/project: kured

commonAnnotations:
  reloader.stakater.com/auto: "true"
