apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
spec:
  project: tools
  sources:
    - repoURL: https://ansible.github.io/awx-operator/
      targetRevision: v2.9.0
      helm:
        releaseName: awx-operator
    - repoURL: "https://github.com/jamie-oconnell/homelab.git"
      targetRevision: main
      ref: values
  destination:
    namespace: awx
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=false
      - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # ignoreDifferences:
  #   - group: admissionregistration.k8s.io
  #     kind: MutatingWebhookConfiguration
  #     jsonPointers:
  #       - /webhooks
  #   - group: apps
  #     kind: Deployment
  #     jsonPointers:
  #       - /spec/replicas
