apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
spec:
  project: default
  sources:
    - repoURL: https://charts.pascaliske.dev
      chart: linkding
      targetRevision: v1.1.0
      helm:
        releaseName: linkding
        # valueFiles:
        #   - $values/apps/argocd/base/tools/linkding.yaml
    # - repoURL: "https://github.com/jamie-oconnell/homelab.git"
    #   targetRevision: main
    #   ref: values
  destination:
    namespace: linkding
    name: in-cluster
  info:
    - name: "Github Repository:"
      value: >-
        https://github.com/pascaliske/helm-charts/
    - name: "Chart location:"
      value: >-
        https://github.com/pascaliske/helm-charts/tree/master/charts/linkding
    - name: "Official Website:"
      value: >-
        https://github.com/sissbruecker/linkding
    - name: "Documentation:"
      value: >-
        https://github.com/sissbruecker/linkding/tree/master/docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    # managedNamespaceMetadata:
    #   labels:
    #     prometheus: enabled
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - Prune=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 15m
