apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    releaseName: prometheus
    includeCRDs: true
    namespace: monitoring
    version: 54.2.2
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values.yaml

namespace: monitoring
