apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/crossplane/crossplane/cluster?ref=v1.15.2

helmCharts:
  - name: crossplane
    releaseName: crossplane
    includeCRDs: false
    version: 1.15.2
    repo: https://charts.crossplane.io/stable
    valuesFile: values.yaml

namespace: crossplane
