apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.image-updater: apiKey
  kustomize.buildOptions: --enable-helm
  application.resourceTrackingMethod: annotation+label
  statusbadge.enabled: "true"
  exec.enabled: "true"
  resource.ignoreResourceUpdatesEnabled: "true"
