apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-core
spec:
  project: monitoring
  source:
    repoURL: "https://github.com/jamie-oconnell/homelab.git"
    path: apps/monitoring/kube-prometheus
    targetRevision: main
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=false
      - Prune=true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 20m
  # See: https://github.com/prometheus-community/helm-charts/issues/1041
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: kube-prometheus-kube-prome-admission
      jsonPointers:
        - /webhooks/0/failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: kube-prometheus-kube-prome-admission
      jsonPointers:
        - /webhooks/0/failurePolicy
