apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/eraser-dev/eraser/v1.2.1/deploy/eraser.yaml

patches:
  - path: overlay/cm-patch.yaml
    target:
      kind: ConfigMap
      name: eraser-config

namespace: eraser-system
