apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-tls
  namespace: linkding
spec:
  secretName: linkding-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: links.jamies.cloud
  dnsNames:
    - links.jamies.cloud
