apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - cert.yaml

helmCharts:
  - name: linkding
    releaseName: linkding
    includeCRDs: false
    version: 1.1.0
    repo: https://charts.pascaliske.dev
    valuesFile: values.yaml

namespace: linkding
