apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

helmCharts:
  - name: external-dns
    releaseName: external-dns-cloudflare
    namespace: networking
    version: 1.15.1
    repo: https://kubernetes-sigs.github.io/external-dns
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/project: external-dns
