apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
spec:
  description: Core Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
  sourceNamespaces:
    - "*"
