apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tools
spec:
  description: Tools related Kubernetes resources
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
  sourceNamespaces:
    - "*"
