apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck
  namespace: rundeck
  labels:
    app: rundeck
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
