apiVersion: v1
kind: Service
metadata:
  name: rundeck-svc
  namespace: rundeck
spec:
  selector:
    app: rundeck
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4440
