apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jamielukeoconnell@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector:
          dnsNames:
            - "*.jamies.cloud"
            - jamies.cloud
            - home.jamies.cloud
            - monitoring.jamies.cloud
            - grafana.jamies.cloud
            - ha.jamies.cloud
            - argo.jamies.cloud
            - links.jamies.cloud
            - n8n.jamies.cloud
        dns01:
          cloudflare:
            email: jamielukeoconnell@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-key-secret
              key: api-key
