---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: ClusterIP
  ingress_type: Ingress
  ingress_annotations: |
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
  hostname: awx.jamies.cloud
  ingress_tls_secret: awx-tls
  ingress_class_name: nginx
