apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awx-tls
  namespace: awx
spec:
  secretName: awx-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: awx.jamies.cloud
  dnsNames:
    - awx.jamies.cloud
