apiVersion: kustomize.config.k8s.io/v1beta1
kind:
  Kustomization
  # ArgoCD Projects
  # - base/projects/home.yaml
  # Core Applications
  # Tools Applications
resources:
  - base/projects/core.yaml
  - base/projects/networking.yaml
  - base/projects/utilities.yaml
  - base/projects/tools.yaml
  - base/core/argocd.yaml
  - base/core/networking.yaml
  - base/core/utilities.yaml
  - base/core/tools.yaml
  - base/tools/awx-operator.yaml
  - base/tools/awx.yaml
namespace: argocd
images:
  - name: quay.io/argoproj/argocd
    newTag: v2.8.4
patches:
  - path: overlay/argocd-svc.yaml
  - path: overlay/argocd-deployment.yaml
  - path: overlay/argocd-cm.yaml
  - path: overlay/argocd-rbac.yaml
  - path: overlay/argocd-cr.yaml
