apiVersion: kustomize.config.k8s.io/v1beta1
kind:
  Kustomization
  # ArgoCD Projects
  # - base/projects/home.yaml
  # Core Applications
  # Tools Applications
resources:
  - base/projects/core.yaml
  - base/projects/networking.yaml
  - base/projects/utilities.yaml
  - base/projects/tools.yaml
  - base/projects/cluster.yaml
  - base/projects/monitoring.yaml
  - base/core/argocd.yaml
  - base/core/networking.yaml
  - base/core/utilities.yaml
  - base/core/tools.yaml
  - base/core/data.yaml

  - base/cmp-plugin.yaml
  - base/repo-role.yaml
  - base/repo-rb.yaml

  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.4/manifests/install.yaml
namespace: argocd
images:
  - name: quay.io/argoproj/argocd
    newTag: v2.8.4

patches:
  - path: overlay/argocd-cr.yaml
    target:
      kind: ClusterRole
      name: argocd-server
  - path: overlay/argocd-svc.yaml
    target:
      kind: Service
      name: argocd-server
  - path: overlay/argocd-deployment.yaml
    target:
      kind: Deployment
      name: argocd-server
  - path: overlay/argocd-repo-deployment.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
  - path: overlay/argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: overlay/argocd-rbac.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - target:
      kind: ServiceMonitor
    patch: |-
      - op: replace
        path: "/metadata/namespace"
        value: "monitoring"
  - patch: |-
      - op: add
        path: "/spec/strategy"
        value:
          type: "Recreate"
      - op: replace
        path: "/spec/template/spec/serviceAccountName"
        value: "argocd-server"
    target:
      kind: Deployment
      name: argocd-server

commonAnnotations:
  reloader.stakater.com/auto: "true"
