apiVersion: kustomize.config.k8s.io/v1beta1
kind:
  Kustomization
  # ArgoCD Projects
  # - base/projects/home.yaml
  # Core Applications
  # Tools Applications
resources:
  - base/projects/core.yaml
  - base/projects/networking.yaml
  - base/projects/utilities.yaml
  - base/projects/tools.yaml
  - base/projects/cluster.yaml
  - base/core/argocd.yaml
  - base/core/networking.yaml
  - base/core/utilities.yaml
  - base/core/tools.yaml
  - base/core/data.yaml
namespace: argocd
images:
  - name: quay.io/argoproj/argocd
    newTag: v2.8.4
patches:
  - path: overlay/argocd-cr.yaml
    target:
      kind: ClusterRole
      name: argocd-server
      namespace: argocd
  - path: overlay/argocd-deployment.yaml
    target:
      kind: Deployment
      name: argocd-server
      namespace: argocd
  - path: overlay/argocd-repo-deployment.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
  - path: overlay/argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
  - path: overlay/argocd-rbac.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
      namespace: argocd
