apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD Projects
  - base/projects/core.yaml
  - base/projects/networking.yaml
  - base/projects/utilities.yaml
  # - base/projects/home.yaml

  # Core Applications
  - base/core/argocd.yaml
  - base/core/networking.yaml
  - base/core/utilities.yaml

namespace: argocd
images:
  - name: quay.io/argoproj/argocd
    newTag: v2.8.4
